module.exports = {
  main_screen: {
    marginTop: 30,
    width: "100%",
    flexDirection: "column",
    backgroundColor: "white",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  main_display: {
    elevation: 10,
    backgroundColor: "#fff",
    width: "95%",
    borderRadius: 10,
    display: "flex",
    padding: 10,
    marginTop: 10,
  },
  main_display_text: {
    fontSize: 50,
    textAlign: "right",
  },
  main_display_keypad: {
    width: "100%",
    height: "70%",
    display: "flex",
  },
  main_display_keypad_row: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
    backgroundColor: "white",
    width: "100%",
    alignItems: "center",
    padding: 10,
  },
  btn_outer: {
    width: 90,
    height: 90,
    backgroundColor: "white",
    elevation: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
  },
  bg_button: {
    backgroundColor: "#fff",
    color: "#000",
    fontSize: 30,
  },
  btn1_outer: {
    width: 90,
    height: 90,
    backgroundColor: "orange",
    elevation: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
  },
  bg1_button: {
    //   backgroundColor
    color: "white",
    fontSize: 30,
    fontWeight: "bold",
  },
  btn2_outer: {
    width: 90,
    height: 90,
    backgroundColor: "grey",
    elevation: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
  },
  bg2_button: {
    color: "white",
    fontSize: 30,
    fontWeight: "bold",
  },
};